name: e_commerce_app
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:

  bloc: ^9.0.0
  awesome_dialog: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^6.0.1
  equatable: ^2.0.5
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_awesome_icon: ^0.0.1
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_intl: ^0.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  meta: ^1.16.0
  modal_progress_hud_nsn: ^0.5.1
  salomon_bottom_bar: ^3.3.2
  smooth_page_indicator: ^1.1.0
  dio: ^5.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fruits.png
    - assets/images/cardFruits.svg
    - assets/images/wallet.svg

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constant/
  filename: assets.dart
  field_prefix: null
