// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-oaPqChRZXT5j5dEPeA1m02WG6igrsI',
    appId: '1:377576775395:web:2e4009da60144cff036fd6',
    messagingSenderId: '377576775395',
    projectId: 'fruits-app-bf710',
    authDomain: 'fruits-app-bf710.firebaseapp.com',
    storageBucket: 'fruits-app-bf710.firebasestorage.app',
    measurementId: 'G-H6B82NQXBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnA-8KGKyCTII4XIuzCHASBdIBk72yCk',
    appId: '1:377576775395:android:b943ab82028cf06a036fd6',
    messagingSenderId: '377576775395',
    projectId: 'fruits-app-bf710',
    storageBucket: 'fruits-app-bf710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJq09XnLcKi5ekjAUARzUk99V0tf0VAg',
    appId: '1:377576775395:ios:c837df9afb465ffe036fd6',
    messagingSenderId: '377576775395',
    projectId: 'fruits-app-bf710',
    storageBucket: 'fruits-app-bf710.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRJq09XnLcKi5ekjAUARzUk99V0tf0VAg',
    appId: '1:377576775395:ios:c837df9afb465ffe036fd6',
    messagingSenderId: '377576775395',
    projectId: 'fruits-app-bf710',
    storageBucket: 'fruits-app-bf710.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-oaPqChRZXT5j5dEPeA1m02WG6igrsI',
    appId: '1:377576775395:web:1e28bfe276a47673036fd6',
    messagingSenderId: '377576775395',
    projectId: 'fruits-app-bf710',
    authDomain: 'fruits-app-bf710.firebaseapp.com',
    storageBucket: 'fruits-app-bf710.firebasestorage.app',
    measurementId: 'G-YDPXX85GFZ',
  );
}
